version: '3.2'

services:
  db:
    build: ./db
    container_name: db
    ports:
      - "3306:3306"
    environment:
        - MYSQL_DATABASE=${MYSQL_DATABASE}
        - MYSQL_USER=${MYSQL_USER}
        - MYSQL_PASSWORD=${MYSQL_PASSWORD}
        - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
  web:
    build: ./app
    container_name: web
    command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py collectstatic && gunicorn main.wsgi -b 0.0.0.0:8000"
    restart: always
    expose:
      - "8000"
    volumes:
      - ./app:/src
    depends_on:
      - db
  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "8000:8000"
    volumes:
      - ./app:/src
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      - web
