version: '3.2'

services:
  web:
    command: bash -c "
      python manage.py makemigrations && 
      python manage.py migrate && 
      python manage.py collectstatic && 
      python manage.py createsuperuser --username Ferenc --noinput --email 'mr.f.kovacs@gmail.com' && 
      gunicorn main.wsgi -b 0.0.0.0:8000 --reload"
  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "8000:8000"
    volumes:
      - ./app:/src
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      - web